// 1,000,000 randomized cases against the EdgeFace alignment/matching math added to
// ../index.html this round: estimateSimilarityTransform (the closed-form 2D Umeyama fit used
// to align a detected face onto EdgeFace's expected 112x112 layout), deriveFaceLandmarks5 (the
// face-api.js 68-point -> 5-point reduction), and matchKnownFaceBest/matchKnownFaceEdge (the
// dual-descriptor matcher that falls back to the original face-api.js descriptor for anyone
// enrolled before EdgeFace existed). Extracted directly out of index.html, not reimplemented.
// Run: node fuzz-face-align.test.js
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf-8');
const start = html.indexOf('const FACE_ALIGN_TEMPLATE');
const end = html.indexOf('async function enrollFaceLocal');
if (start < 0 || end < 0) throw new Error('Could not find face-matching markers in index.html');
const src = html.slice(start, end) + '\nmodule.exports = { deriveFaceLandmarks5, estimateSimilarityTransform, cosineSimilarity, matchKnownFaceEdge, matchKnownFaceBest };';
const sandbox = { module: { exports: {} } };
vm.createContext(sandbox);
vm.runInContext(src, sandbox, { filename: 'index.html(extracted)' });
const { deriveFaceLandmarks5, estimateSimilarityTransform, cosineSimilarity, matchKnownFaceEdge, matchKnownFaceBest } = sandbox.module.exports;
for (const [name, fn] of Object.entries({ deriveFaceLandmarks5, estimateSimilarityTransform, cosineSimilarity, matchKnownFaceEdge, matchKnownFaceBest })) {
  if (typeof fn !== 'function') throw new Error(name + ' did not extract as a function');
}

let pass = 0, fail = 0;
function check(name, cond, detail) {
  if (cond) { pass++; }
  else { fail++; console.log('FAIL  ' + name + (detail !== undefined ? '  -> ' + JSON.stringify(detail) : '')); }
}

const SEED = 20261001;
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(SEED);
function randInt(min, max) { return Math.floor(rand() * (max - min + 1)) + min; }
function randFloat(min, max) { return rand() * (max - min) + min; }

console.log('Seed: ' + SEED + ' (re-run with this seed to reproduce any failure)\n');

// ---------- estimateSimilarityTransform: round-trip a known random transform ----------
// A similarity transform has exactly 4 degrees of freedom (scale, rotation, tx, ty). Fitting
// >=2 points that were generated BY one specific transform, with no noise, must recover that
// exact transform (up to floating-point error) - this is the real invariant, not just "doesn't
// throw". A classic face-landmark-shaped point set (5 points, roughly eyes/nose/mouth layout)
// is used as the base so the fuzz matches the function's real call site.
const N1 = 300000;
const BASE_PTS = [{ x: 38, y: 52 }, { x: 74, y: 52 }, { x: 56, y: 72 }, { x: 42, y: 92 }, { x: 71, y: 92 }];
for (let i = 0; i < N1; i++) {
  const scale = randFloat(0.3, 3);
  const angle = randFloat(-Math.PI, Math.PI);
  const tx = randFloat(-500, 500), ty = randFloat(-500, 500);
  const ca = Math.cos(angle) * scale, sa = Math.sin(angle) * scale;
  const dst = BASE_PTS.map(p => ({ x: ca * p.x - sa * p.y + tx, y: sa * p.x + ca * p.y + ty }));

  let t;
  try { t = estimateSimilarityTransform(BASE_PTS, dst); }
  catch (e) { check('estimateSimilarityTransform#' + i + ' does not throw', false, { scale, angle, tx, ty, error: e.message }); continue; }

  check('estimateSimilarityTransform#' + i + ' recovers the exact generating transform', t &&
    Math.abs(t.a - ca) < 1e-6 && Math.abs(t.b - sa) < 1e-6 &&
    Math.abs(t.tx - tx) < 1e-6 * Math.max(1, Math.abs(tx)) && Math.abs(t.ty - ty) < 1e-6 * Math.max(1, Math.abs(ty)),
    { generated: { ca, sa, tx, ty }, got: t });

  // Applying the recovered transform to BASE_PTS must land back on dst (the actual contract
  // alignFaceCrop relies on - not just "parameters look right").
  if (t) {
    let worst = 0;
    for (let k = 0; k < BASE_PTS.length; k++) {
      const p = BASE_PTS[k], want = dst[k];
      const gotX = t.a * p.x - t.b * p.y + t.tx, gotY = t.b * p.x + t.a * p.y + t.ty;
      worst = Math.max(worst, Math.abs(gotX - want.x), Math.abs(gotY - want.y));
    }
    check('estimateSimilarityTransform#' + i + ' reprojects within tolerance', worst < 1e-4 * Math.max(1, scale), worst);
  }
}

// Malformed/degenerate inputs must never throw and must always return null.
const N2 = 200000;
function randBadPoint() {
  const variants = [null, undefined, {}, { x: NaN, y: 0 }, { x: Infinity, y: 0 }, { x: 'a', y: 0 }, { x: 0, y: 0 }];
  return variants[randInt(0, variants.length - 1)];
}
for (let i = 0; i < N2; i++) {
  const n = randInt(0, 6);
  const src = Array.from({ length: n }, () => randBadPoint());
  const dst = Array.from({ length: randInt(0, 6) }, () => randBadPoint());
  let t;
  try { t = estimateSimilarityTransform(src, dst); }
  catch (e) { check('estimateSimilarityTransform#malformed' + i + ' does not throw', false, { src, dst, error: e.message }); continue; }
  const allGood = src.length === dst.length && src.length >= 2 && src.every(p => p && Number.isFinite(p.x) && Number.isFinite(p.y)) && dst.every(p => p && Number.isFinite(p.x) && Number.isFinite(p.y));
  if (!allGood) check('estimateSimilarityTransform#malformed' + i + ' rejects bad input with null', t === null, { src, dst, got: t });
}

// ---------- deriveFaceLandmarks5: random 68-point arrays, with occasional holes ----------
const N3 = 150000;
for (let i = 0; i < N3; i++) {
  const hasHole = i % 5 === 0;
  const holeAt = hasHole ? [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 30, 48, 54][randInt(0, 14)] : -1;
  const pts = Array.from({ length: randInt(0, 70) }, (_, idx) => idx === holeAt ? null : { x: randFloat(-1000, 1000), y: randFloat(-1000, 1000) });

  let out;
  try { out = deriveFaceLandmarks5(pts); }
  catch (e) { check('deriveFaceLandmarks5#' + i + ' does not throw', false, { len: pts.length, holeAt, error: e.message }); continue; }

  if (pts.length < 68 || hasHole) {
    check('deriveFaceLandmarks5#' + i + ' rejects short/holed input with null', out === null, { len: pts.length, holeAt, got: out });
  } else {
    check('deriveFaceLandmarks5#' + i + ' returns exactly 5 points', Array.isArray(out) && out.length === 5, out);
    if (Array.isArray(out)) {
      check('deriveFaceLandmarks5#' + i + ' nose matches index 30 exactly', out[2].x === pts[30].x && out[2].y === pts[30].y);
      check('deriveFaceLandmarks5#' + i + ' left mouth matches index 48 exactly', out[3].x === pts[48].x && out[3].y === pts[48].y);
      check('deriveFaceLandmarks5#' + i + ' right mouth matches index 54 exactly', out[4].x === pts[54].x && out[4].y === pts[54].y);
    }
  }
}

// ---------- matchKnownFaceBest: the dual-descriptor fallback behavior ----------
const N4 = 350000;
function normalize(v) { const n = Math.sqrt(v.reduce((s, x) => s + x * x, 0)); return n > 1e-9 ? v.map(x => x / n) : v; }
function randVec(dim) { return normalize(Array.from({ length: dim }, () => randFloat(-1, 1))); }
for (let i = 0; i < N4; i++) {
  const numPeople = randInt(0, 4);
  const knownFaces = Array.from({ length: numPeople }, (_, idx) => {
    const kf = { name: 'Person' + idx, descriptor: Array.from({ length: 4 }, () => randFloat(-2, 2)) };
    if (rand() < 0.5) kf.edge = randVec(8); // only some have the new embedding - the realistic mixed-enrollment case
    return kf;
  });
  const hasEdge = rand() < 0.6;
  const captured = { descriptor: Array.from({ length: 4 }, () => randFloat(-2, 2)) };
  if (hasEdge) captured.edge = randVec(8);

  let result;
  try { result = matchKnownFaceBest(captured, knownFaces); }
  catch (e) { check('matchKnownFaceBest#' + i + ' does not throw', false, { captured, knownFaces, error: e.message }); continue; }

  check('matchKnownFaceBest#' + i + ' result is null or names an enrolled person', result === null || knownFaces.some(kf => kf.name === result.name), { result, knownFaces });
  check('matchKnownFaceBest#' + i + ' status is always confirmed/candidate when matched', result === null || result.status === 'confirmed' || result.status === 'candidate', result);

  // Cross-check: if the edge-preferring path would find a confident match, matchKnownFaceBest
  // must return exactly that match (never silently prefer the weaker legacy one instead).
  if (hasEdge) {
    const edgeOnly = matchKnownFaceEdge(captured.edge, knownFaces);
    if (edgeOnly) check('matchKnownFaceBest#' + i + ' returns the edge match when one exists', result && result.name === edgeOnly.name && result.status === edgeOnly.status, { result, edgeOnly });
  }
}

console.log('\n' + pass + ' passed, ' + fail + ' failed (out of ' + (pass + fail) + ' total checks across ' + (N1 + N2 + N3 + N4) + ' randomized cases)');
process.exit(fail ? 1 : 0);
